"""add_product_stock_count

Revision ID: 58713a048da0
Revises: c1777f517948
Create Date: 2026-03-06 07:40:54.552585

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58713a048da0'
down_revision: Union[str, None] = 'c1777f517948'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_count', sa.Numeric(precision=10, scale=3), nullable=False, server_default='0'))

    # FK already enforced at DB level via PRAGMA foreign_keys=ON

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('stock_count')

    # ### end Alembic commands ###
